{% set name = "paraview-trame-components" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paraview_trame_components-{{ version }}.tar.gz
  sha256: 55bccfc58be6c8fcb3a2b6556cc8451fc2b1ff756a7da1b2f1f8474c499ab0ef

build:
  entry_points:
    - ptc-lite = ptc.apps.lite:main
    - ptc-demo = ptc.apps.demo:main
    - ptc-sphere = ptc.apps.sphere:main
    - ptc-state = ptc.apps.state_loader:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - trame
    - trame-vtk
    - trame-vuetify
    - trame-components
    - paraview

test:
  imports:
    - ptc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/paraview-trame-components
  summary: Macro components for ParaView
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
